# Generated by Django 4.2.7 on 2023-11-21 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('courseNumber', models.IntegerField()),
                ('semester', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionNumber', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('daysMeeting', models.CharField(max_length=7)),
                ('startTime', models.CharField(max_length=50)),
                ('endTime', models.CharField(max_length=50)),
                ('assignedUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='SchedulingApp.myuser')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchedulingApp.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='assignedUser',
            field=models.ManyToManyField(null=True, to='SchedulingApp.myuser'),
        ),
    ]
