# Generated by Django 4.2.7 on 2023-11-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='defaultaddress', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='courseNumber',
            field=models.IntegerField(default=1234, editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(default='defaultdept', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='defaultcoursename', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(default='defaultsemester', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(default='default@uwm.edu', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='firstName',
            field=models.CharField(default='defaultfirstname', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lastName',
            field=models.CharField(default='defaultlastname', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phoneNumber',
            field=models.CharField(default='defaultphonenumber', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(default='defaultrole', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='daysMeeting',
            field=models.CharField(default='MWTHF', max_length=7),
        ),
        migrations.AlterField(
            model_name='section',
            name='endTime',
            field=models.CharField(default='defaultendtime', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='location',
            field=models.CharField(default='defaultlocation', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionNumber',
            field=models.IntegerField(default=1234, editable=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='startTime',
            field=models.CharField(default='defaultstarttime', max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(default='defaultsectype', max_length=20),
        ),
    ]
