# Generated by Django 4.2.7 on 2023-11-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseNumber',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(default='LATIN', max_length=12),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='Default Course Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter')], default='Spring', max_length=6),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(default='default@uwm.edu', max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='streetAddress',
            field=models.CharField(default='1234 Main st', max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='location',
            field=models.CharField(default='defaultlocation', max_length=100),
        ),
    ]
