# Generated by Django 4.2.7 on 2023-11-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0002_myuser_address_alter_course_coursenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseNumber',
            field=models.IntegerField(default=1234),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.CharField(default='defaultdept', max_length=20),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.CharField(default='default@uwm.edu', max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionNumber',
            field=models.IntegerField(default=1234),
        ),
    ]
