# Generated by Django 4.2.7 on 2023-12-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0002_alter_course_coursenumber_alter_course_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(default='53206', max_length=10),
        ),
    ]
