# Generated by Django 4.2.7 on 2023-11-21 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0003_alter_course_coursenumber_alter_course_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='address',
            field=models.CharField(default='defaultaddress', max_length=50),
        ),
    ]
