# Generated by Django 4.2.7 on 2023-12-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0003_alter_myuser_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.CharField(default='No bio added', max_length=500),
        ),
    ]
