# Generated by Django 4.2.7 on 2023-11-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0004_alter_myuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('ad', 'Admin'), ('in', 'Instructor'), ('ta', 'TA')], default='admin', max_length=2),
        ),
    ]
