# Generated by Django 4.2.7 on 2023-12-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0004_myuser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(default='No bio added', max_length=500),
        ),
    ]
