# Generated by Django 4.2.7 on 2023-11-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchedulingApp', '0005_alter_myuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='address',
        ),
        migrations.AddField(
            model_name='myuser',
            name='city',
            field=models.CharField(default='Milwaukee', max_length=20),
        ),
        migrations.AddField(
            model_name='myuser',
            name='state',
            field=models.CharField(default='WI', max_length=2),
        ),
        migrations.AddField(
            model_name='myuser',
            name='streetAddress',
            field=models.CharField(default='1234 main st', max_length=50),
        ),
        migrations.AddField(
            model_name='myuser',
            name='zipcode',
            field=models.IntegerField(default=53206),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='defaultcoursename', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('sp', 'Spring'), ('su', 'Summer'), ('fa', 'Fall'), ('wi', 'Winter')], default='fa', max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('ad', 'Admin'), ('in', 'Instructor'), ('ta', 'TA')], default='ad', max_length=2),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionNumber',
            field=models.IntegerField(default=400),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('le', 'Lecture'), ('gr', 'Grader'), ('se', 'Section')], default='le', max_length=2),
        ),
    ]
